# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(),
        ),
    ]
