# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Request',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=5)),
                ('driver_id', models.CharField(max_length=20)),
                ('driver_lat', models.CharField(max_length=200)),
                ('driver_long', models.CharField(max_length=200)),
                ('source_lat', models.CharField(max_length=200)),
                ('source_long', models.CharField(max_length=200)),
                ('destination_lat', models.CharField(max_length=200)),
                ('destination_long', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('actual_fare', models.CharField(max_length=10)),
                ('driver_accept', models.CharField(max_length=100)),
                ('payment_done', models.BooleanField(default=False)),
            ],
        ),
    ]
