# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_request', '0002_driver_request_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_request',
            name='actual_fare',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
