# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_request', '0003_driver_request_actual_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_request',
            name='actual_fare',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
